# Generated by Django 4.0.3 on 2022-04-26 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinationsRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='registration',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='Comorbidities',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='cellularPhone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registration',
            name='covidInfections',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='landLine',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registration',
            name='zipCode',
            field=models.CharField(max_length=255),
        ),
    ]
